export const PHASES = {
  idea: {
    slug: "idea",
    title: "Ideia",
    color: "#fbbf24",
    order: 1,
    shortcut: "i",
    key: "KeyI",
  },
  do: {
    slug: "do",
    title: "Fazer",
    color: "#f97316",
    order: 2,
    shortcut: "f",
    key: "KeyF",
  },
  doing: {
    slug: "doing",
    title: "Fazendo",
    color: "#ec4899",
    order: 3,
    shortcut: "z",
    key: "KeyZ",
  },
  review: {
    slug: "review",
    title: "Análise",
    color: "#a855f7",
    order: 4,
    shortcut: "a",
    key: "KeyA",
  },
  done: {
    slug: "done",
    title: "Feito",
    color: "#38bdf8",
    order: 5,
    shortcut: "t",
    key: "KeyT",
  },
  finished: {
    slug: "finished",
    title: "Concluído",
    color: "#4ade80",
    order: 6,
    shortcut: "c",
    key: "KeyC",
  },
} as const;
export type PHASE = keyof typeof PHASES;
export type PHASE_TYPE = (typeof PHASES)[PHASE];
export const CATEGORIES = {
  ads: {
    slug: "ads",
    title: "Tráfego Pago",
    shortcut: "a",
    color: "#0099ff",
    area: "account",
    tag: "ADS",
    tag_min: "ad",
  },
  capture: {
    slug: "capture",
    title: "Gravação",
    shortcut: "u",
    color: "#00ffc4",
    area: "creative",
    tag: "REC",
    tag_min: "gr",
  },
  carousel: {
    slug: "carousel",
    title: "Carrossel",
    shortcut: "c",
    color: "#ff0071",
    area: "creative",
    tag: "CRSL",
    tag_min: "cr",
  },
  design: {
    slug: "design",
    title: "Design",
    shortcut: "d",
    color: "#ff0080",
    area: "creative",
    tag: "DSGN",
    tag_min: "dg",
  },
  dev: {
    slug: "dev",
    title: "Tech/Coding",
    shortcut: "g",
    color: "#b1ff00",
    area: "creative",
    tag: "TECH",
    tag_min: "tc",
  },
  finance: {
    slug: "finance",
    title: "Financeiro",
    shortcut: "f",
    color: "#46b95d",
    area: "adm",
    tag: "FINC",
    tag_min: "fn",
  },
  meeting: {
    slug: "meeting",
    title: "Reunião",
    shortcut: "m",
    color: "#375bc8",
    area: "account",
    tag: "REUN",
    tag_min: "re",
  },
  post: {
    slug: "post",
    title: "Post Estático",
    shortcut: "p",
    color: "#ff4000",
    area: "creative",
    tag: "POST",
    tag_min: "pt",
  },
  print: {
    slug: "print",
    title: "Impresso",
    shortcut: "i",
    color: "#cc33aa",
    area: "creative",
    tag: "IMPR",
    tag_min: "im",
  },
  reels: {
    slug: "reels",
    title: "Reels",
    shortcut: "r",
    color: "#aa00ff",
    area: "creative",
    tag: "REEL",
    tag_min: "rl",
  },
  sm: {
    slug: "sm",
    title: "Social Media",
    shortcut: "l",
    color: "#ff0015",
    area: "account",
    tag: "SOCI",
    tag_min: "sm",
  },
  stories: {
    slug: "stories",
    title: "Stories",
    shortcut: "s",
    color: "#aacc33",
    area: "creative",
    tag: "STOR",
    tag_min: "st",
  },
  todo: {
    slug: "todo",
    title: "Tarefa",
    shortcut: "t",
    color: "#0088ff",
    area: "account",
    tag: "TASK",
    tag_min: "ta",
  },
} as const;
export type CATEGORY = keyof typeof CATEGORIES;
export type CATEGORY_TYPE = (typeof CATEGORIES)[CATEGORY];
export const PRIORITIES = {
  low: {
    slug: "low",
    title: "Baixa",
    shortcut: ",",
  },
  medium: {
    slug: "medium",
    title: "Média",
    shortcut: ".",
  },
  high: {
    slug: "high",
    title: "Alta",
    shortcut: "/",
  },
} as const;
export type PRIORITY = keyof typeof PRIORITIES;
export type PRIORITY_TYPE = (typeof PRIORITIES)[PRIORITY];
export const AREAS = {
  adm: {
    slug: "adm",
    title: "Administrativo",
    role: 1,
  },
  account: {
    slug: "account",
    title: "Atendimento",
    role: 2,
  },
  creative: {
    slug: "creative",
    title: "Criação",
    role: 3,
  },
} as const;
export type AREA = keyof typeof AREAS;
export type AREA_TYPE = (typeof AREAS)[AREA];
export const SIZE = {
  xs: "xs",
  sm: "sm",
  md: "md",
  lg: "lg",
  xl: "xl",
  "2xl": "2xl",
} as const;
export const DATE_TIME_DISPLAY = {
  Relative: 1,
  DateTime: 2,
  DateMonthTime: 3,
  DayDateMonthTime: 4,
  DayDate: 5,
  TimeOnly: 6,
  DateOnly: 7,
  Null: 8,
} as const;
export const VARIANT = {
  line: "line",
  block: "block",
  content: "content",
  hair: "hair",
} as const;
export const INTENT = {
  create_action: "create-action",
  update_action: "update-action",
  bulk_update_actions: "bulk-update-actions",
  bulk_update_date_only: "bulk-update-date-only",
  bulk_update_time_only: "bulk-update-time-only",
  duplicate_action: "duplicate-action",
  delete_action: "delete-action",
  create_comment: "create-comment",
  update_comment: "update-comment",
  delete_comment: "delete-comment",
  ai_caption: "ai-caption",
  ai_content: "ai-content",
  ai_hooks: "ai-hooks",
  ai_strategy: "ai-strategy",
  ai_post: "ai-post",
  ai_carousel: "ai-carousel",
  ai_stories: "ai-stories",
  ai_reels: "ai-reels",
  mark_notification_read: "mark-notification-read",
  mark_all_notifications_read: "mark-all-notifications-read",
} as const;
export const ORDER_BY = {
  date: "date",
  priority: "priority",
  phase: "phase",
} as const;
export const PALLETE = [
  {
    id: "default",
    label: "Padrão",
    light: {
      primary: {
        h: 0,
        c: 0,
        l: 0,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 200,
        c: 0.002,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.1,
      popoverLDelta: 0.02,
    },
    dark: {
      primary: {
        h: 0,
        c: 0,
        l: 1,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 250,
        c: 0.01,
        l: 0.2,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.1,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "energy",
    label: "Energy",
    light: {
      primary: {
        h: 120,
        c: 0.26,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 240,
        c: 0.001,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 120,
        c: 0.26,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 250,
        c: 0.01,
        l: 0.2,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "blue",
    label: "Azul (Padrão)",
    light: {
      primary: {
        h: 264,
        c: 0.31,
        l: 0.45,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 1,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: -0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0.1,
    },
    dark: {
      primary: {
        h: 264,
        c: 0.31,
        l: 0.58,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "purple",
    label: "Roxo",
    light: {
      primary: {
        h: 290,
        c: 0.28,
        l: 0.54,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 1,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.1,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 290,
        c: 0.28,
        l: 0.68,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "magenta",
    label: "Magenta",
    light: {
      primary: {
        h: 350,
        c: 0.4,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 320,
        c: 0.02,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 350,
        c: 0.4,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 340,
        c: 0.1,
        l: 0.3,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "red",
    label: "Vermelho",
    light: {
      primary: {
        h: 20,
        c: 0.25,
        l: 0.62,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.04,
      actionHoverLDelta: 0.06,
      popoverLDelta: 0.06,
    },
    dark: {
      primary: {
        h: 20,
        c: 0.25,
        l: 0.68,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "orange",
    label: "Laranja",
    light: {
      primary: {
        h: 25,
        c: 0.18,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 130,
        c: 0.01,
        l: 0.95,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 1,
      popoverLDelta: 0.03,
    },
    dark: {
      primary: {
        h: 25,
        c: 0.18,
        l: 0.65,
      },
      primaryFg: {
        h: 130,
        c: 0.02,
        l: 0.9,
      },
      bg: {
        h: 190,
        c: 0.01,
        l: 0.25,
      },
      fg: {
        h: 130,
        c: 0.01,
        l: 0.95,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.1,
      inputLDelta: -0.05,
      actionLDelta: 0.07,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "yellow",
    label: "Amarelo",
    light: {
      primary: {
        h: 100,
        c: 0.5,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 100,
        c: 0.4,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "green",
    label: "Verde",
    light: {
      primary: {
        h: 130,
        c: 0.2,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 130,
        c: 0.2,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "cyan",
    label: "Ciano",
    light: {
      primary: {
        h: 200,
        c: 0.2,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 200,
        c: 0.2,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "light-blue",
    label: "Azul Claro",
    light: {
      primary: {
        h: 260,
        c: 0.22,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 240,
        c: 0.22,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "navy",
    label: "Azul Marinho",
    light: {
      primary: {
        h: 250,
        c: 0.12,
        l: 0.5,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 90,
        c: 0.005,
        l: 0.99,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 250,
        c: 0.12,
        l: 0.6,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
];
export const HOOKS = [
  {
    id: "aca86e03-4d6d-4717-b72b-c7fadccdbae9",
    title: "Tour completo por dentro do [PRODUTO/CURSO/MENTORIA/SERVIÇO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "52bd18b5-f75e-4639-9aa7-30eaded81414",
    title:
      "Como conquistar [RESULTADO/OBJETIVO/CONQUISTA] mesmo começando do zero",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "bbd11a51-a7bb-4652-b716-b32ce47159a0",
    title:
      "O que eu observo em [CLIENTES/PACIENTES/ALUNOS] que travam sempre no mesmo ponto",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: ["Consultoria", "Mentoria", "Serviço"],
  },
  {
    id: "28ca9edd-04e9-42f2-ac29-f68a97713dac",
    title: "Qual dos meus [PRODUTOS/SERVIÇOS] é o ideal para você?",
    niche: [],
    goal: "Vender",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "f5a31183-a63b-4932-beff-e62bf05ce0c2",
    title: "Transformações que começaram com um diagnóstico gratuito",
    niche: [
      "Direito",
      "Educação",
      "Infoprodutor",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "d4b66e4c-052d-47ad-a05f-a1ebe8b6c6f0",
    title: "O tipo de resultado que você pode esperar do [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "75078adf-1acb-4304-b6df-e41e624bb00e",
    title:
      "O que eu fiz para gerar [RESULTADO/FATURAMENTO/CLIENTES] todos os meses",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "4e729153-0073-41c4-8ebd-3a6e30bb7790",
    title: "Resultados inesperados da minha [MENTORIA/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Mentoria", "Serviço"],
  },
  {
    id: "37f9cbd1-3363-4028-8530-433faae2a06f",
    title:
      "Comparativo: o jeito que a maioria faz [AÇÃO/ESTRATÉGIA/PROCESSO] vs. o jeito que realmente funciona",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "4c6ee208-c9a8-4783-9f88-5d61ea0a3b87",
    title:
      "3 ajustes que me fizeram começar a ver resultado com [X] em poucos dias",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "ab3bb3d7-8bd3-486b-b2be-bd635ebece08",
    title: "Os 3 passos que eu seguiria se estivesse começando hoje em [NICHO]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "25240ae6-4b4f-4bbf-b74a-39712cd3ae43",
    title: "Conselhos que eu te daria se fôssemos amigos",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "35f202f3-2d52-4e75-ad2b-3108226422ed",
    title:
      "O que eu observei nos [ALUNOS/CLIENTES] que mais tiveram resultado com o [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "a43dea50-c99e-4e89-8640-6d1e2332e77e",
    title: "Antes e depois de aplicar o [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "f8c75414-7b47-4ec2-b894-3f3ce8f809db",
    title: "Quem mais precisa do [PRODUTO/SERVIÇO] hoje",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "f2775eb3-0251-4944-8f06-3a7407595139",
    title: "As 3 decisões que mudaram completamente o meu [OBJETIVO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "8e2b837f-f48c-4a3c-92e1-83ba003a0063",
    title: "Quem pode (e quem não pode) participar do [PRODUTO/SERVIÇO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "af368e21-8a67-4983-b0cd-a9da1c2160c3",
    title: "O que acontece depois que você faz um diagnóstico comigo",
    niche: [
      "Direito",
      "Educação",
      "Infoprodutor",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "ac50c806-eea6-4f93-bfbc-0cdc22815e3c",
    title: "Pra quem é (e pra quem não é) o [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "0733d80b-063b-4d50-8dd3-c3714f67de93",
    title:
      "Sinais de que você precisa de um diagnóstico/[CONSULTA/AVALIAÇÃO] do seu [NEGÓCIO/CONTEÚDO/SAÚDE]",
    niche: [
      "Direito",
      "Educação",
      "Infoprodutor",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "75ba7ff5-cc7c-4e0c-aa20-550489f3967e",
    title:
      "Prints que mostram o que acontece dentro da [MENTORIA/CONSULTORIA/GRUPO/ACOMPANHAMENTO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "01df3116-748e-4f27-b1da-ffa401c21a8d",
    title:
      "Mensagens que recebo todos os dias de quem está na [MENTORIA/CONSULTORIA/PROGRAMA]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "85d180e8-87ec-4e9d-8d84-f023a8c2da5e",
    title: "O que você precisa ouvir (mesmo que doa um pouco)",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "ecec71c5-7d8e-4408-9493-70e52ea000de",
    title: "Problemas que eu já resolvi em um Diagnóstico gratuito",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "6768f242-19f9-4ebe-a64b-ca55c7ed3bf7",
    title:
      "O que eu fiz para alcançar [RESULTADO/OBJETIVO] como [PROFISSÃO/ESPECIALISTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "4c58f527-0d54-4ae6-9d8f-c725481f7933",
    title: "Faça isso para alcançar [RESULTADO/OBJETIVO/TRANSFORMAÇÃO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "6ec9c403-ff48-4084-aa64-b59c7b8f2930",
    title:
      "O que eu gostaria de ter aprendido antes como [PROFISSÃO/ESPECIALISTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "bbad8ec1-f4d5-4b5a-bccf-89c818b6f564",
    title:
      "Espiando o que acontece dentro do grupo dos meus [MENTORADOS/CLIENTES]",
    niche: [],
    goal: "Vender",
    productType: [],
  },
  {
    id: "b64b4c6a-e869-4e16-bcad-fed728541fdb",
    title:
      "O que aconteceu quando [NOME DO ALUNO/CLIENTE/PACIENTE] aplicou o [PRODUTO/MÉTODO] por [X DIAS]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "41fedc37-cbb8-43c2-a88b-a408d6d889fc",
    title: "Troque [X] por [Y]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "ba8544e2-3ba5-42d3-85a7-a429454ebe50",
    title:
      "[X] mitos sobre [RESULTADO/OBJETIVO/CONQUISTA] que você precisa esquecer agora",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "14155809-f2dd-44c1-a7d8-44514735b61f",
    title: "Bastidores do mês de [MÊS] dentro do [PRODUTO/SERVIÇO]”",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "6437d84b-c691-4f52-9f8a-722620c006e7",
    title: "Um problema x Uma solução do meu [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "3cddbc08-4807-453b-9343-00e88ff08351",
    title: "Troque [PENSAMENTO LIMITANTE] por [NOVO PENSAMENTO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "d08ed1f9-1d2f-42f2-a23e-a23c66ab08f9",
    title:
      "Conselhos que eu te daria se você fosse meu [ALUNO/CLIENTE/PACIENTE]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "b365c6c8-5590-40a1-a8f2-a468e551e183",
    title: "Atualizações que aconteceram no [PRODUTO/SERVIÇO] recentemente",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "010f303d-2bd3-4dbf-9a0a-00af409b075b",
    title: "O que realmente acontece dentro de um diagnóstico",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "13362e42-4c9b-4356-8a46-91f79d2cb03e",
    title: "O que as pessoas dizem depois de fazer um diagnóstico comigo",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "d1761737-5dff-4d01-9718-9b93ce734ff5",
    title: "Troque [ERRO] pelo [ACERTO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "109b4a69-0be8-41af-9a7a-422ce0f656ae",
    title:
      "Os [CLIENTES/PACIENTES] que eu já atendi e as [ESTRATÉGIAS] que usamos pra eles",
    niche: [],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "6b51f5f0-a651-4551-9087-7003b8a52ba9",
    title: "Erros que eu enxergo quando estou fazendo [ATIVIDADE]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "360b36c4-bb09-4a77-95b4-b295ebd57397",
    title: "[ESTRATÉGIAS] que eu fiz para o [NICHO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "9e90b30f-b2c9-4bdd-9fda-53c120d0d948",
    title: "POV: Você está assistindo uma aula do [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "5a2fbcdb-fb30-4bcb-a8dd-bf0777d75a8b",
    title: "Coisas que eu parei de fazer como [PROFISSÃO/ESPECIALISTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "b062e95b-a817-4635-b78c-aa9d40c52481",
    title: "3 ideias que me ajudaram a começar a [AÇÃO] com confiança",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "c52127b2-0f61-42a5-9278-33d437f955d6",
    title: "O que você conquista em [TEMPO] depois da [MENTORIA/SERVIÇO]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Mentoria", "Serviço"],
  },
  {
    id: "dd79e12f-079d-4f99-9820-26e1b16636ab",
    title: "3 verdades que ninguém te contou sobre [TEMA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "a710e47a-39a1-43dd-aa04-61195ca4a888",
    title:
      "Erros que eu não deixaria você cometer se fosse meu [ALUNO/CLIENTE]",
    niche: [],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "a04ae1db-ef1e-45dc-8317-59935824dff2",
    title:
      "O que as pessoas percebem durante o diagnóstico/[CONSULTA/SESSÃO/ATENDIMENTO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "e35a7a59-4583-4be4-a152-8793b4b4dd99",
    title: "Problemas que meu [PRODUTO/SERVIÇO] resolve e você não sabia",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "a53cc2c5-c76d-4026-8023-d80ca982f47a",
    title:
      "Antes e depois de entrar na [MENTORIA/CONSULTORIA/PROGRAMA/ACOMPANHAMENTO]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "637ed895-86d4-405b-9cf9-3b10559ed370",
    title: "Você está tentando resolver o [PROBLEMA] errado.",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "3918192e-6d6b-4198-bf5c-37647f4b6797",
    title:
      "O que ninguém te conta sobre a fase de [INÍCIO/TRANSIÇÃO/CRESCIMENTO] em [NICHO/ÁREA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "c4dd465d-49fc-45aa-827c-bcffb1acd458",
    title: "O básico sobre [AÇÃO] explicado em menos de 5 minutos",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "be3fcd55-8838-48d3-ac94-5cb7abfba6c6",
    title:
      "Ele(a) conquistou [RESULTADO/OBJETIVO/CONQUISTA] sem precisar [OBJEÇÃO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "5153cb12-ffb2-4db7-b9f3-ad10fea16ad8",
    title: "As 5 dores de quem tenta [AÇÃO] sem uma [ESTRATÉGIA]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "ef785f06-7121-4c3f-a773-ca7e0000bf4a",
    title:
      "Por que você não está vendo resultado em [TEMA] (mesmo fazendo tudo certo)",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "ad5bb2c5-477b-446b-ab60-fb8ec64fbf95",
    title:
      "Análise: o que está por trás do [RESULTADO/CASO/TENDÊNCIA] que todo mundo está falando",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "602eab5d-f188-49fe-a2b2-77aedbbbb482",
    title: "Conquistas dos meus [MENTORADOS/CLIENTES] que vão além do dinheiro",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "bbeba54e-f959-41d9-8b55-bef6b2d46376",
    title: "Como seria o seu diagnóstico comigo (passo a passo)",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "35697f8c-0e6d-4d4a-b81c-ab253499c3dd",
    title:
      "5 passos para alcançar [RESULTADO/OBJETIVO/CONQUISTA] ainda esse mês",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "70ff9912-83cf-4e61-9ce1-1b7decedcc56",
    title:
      "Termos sobre [NICHO/ÁREA] que toda [PROFISSÃO/ESPECIALISTA] precisa conhecer",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "a661dbf7-f5a2-45f3-a9b1-eb0de59d9ead",
    title: "O checklist essencial para começar a [AÇÃO] do jeito certo",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "8bf97fa1-6c71-42b6-b820-69d9a1788315",
    title: "[X] coisas que você precisa saber antes de tentar [AÇÃO]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "c2ec09ab-de47-4248-8094-b52c141e585c",
    title: "[X] verdades sobre [RESULTADO/OBJETIVO/CONQUISTA] que ninguém fala",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "ec90df7b-abd6-4d8b-94eb-1d7ddfed48cd",
    title:
      "A [ESTRATÉGIA/TÉCNICA/ABORDAGEM] que mais gera [RESULTADO/OBJETIVO/CONQUISTA] em menos tempo",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "5761b456-e82e-4b60-8160-6903a9501ce8",
    title:
      "[X] mitos sobre [RESULTADO/OBJETIVO/CONQUISTA] que você precisa esquecer agora",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "435f0ef2-f24c-40b5-ba72-84c44add8aa2",
    title:
      "Troque esses hábitos se você quer chegar em [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "27c97b9d-792a-4766-a586-7b59da0bf2cb",
    title:
      "A virada que aconteceu quando parei de [AÇÃO ERRADA] e comecei a [AÇÃO CERTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "3d508b7a-e482-4378-b104-e70465349cc4",
    title: "Coisas que eu estou amando fazer como [PROFISSÃO/ESPECIALISTA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "5d5df768-4f5a-4240-b4cb-c1ff99e7b7a4",
    title: "Roube as minhas anotações sobre [EVENTO/FILME/LIVRO/PALESTRA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "de0a2527-fc33-4ac3-801f-808b96dc77b1",
    title:
      "Transformações que aconteceram depois de entrar na [MENTORIA/CONSULTORIA/ACOMPANHAMENTO]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "d945d1ca-52b9-4f0a-b4d1-814dbe284520",
    title:
      "3 erros que me faziam trabalhar o dobro e lucrar a metade como [PROFISSÃO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "386f5346-7c6b-45e5-a601-0c297f4821f0",
    title:
      "Como criar uma [ESTRATÉGIA/ROTINA/ABORDAGEM] que gera [RESULTADO/OBJETIVO/CONQUISTA] todos os dias",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "3c8b1bf0-d6bc-40b3-9aa6-ddca120525d1",
    title: "[X] lições que aprendi com [X] anos de [PROFISSÃO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "0312b7d3-44f4-48cc-a0d4-604a9ff4aedf",
    title: "Como fazer [AÇÃO] sem precisar de [OBJEÇÃO]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "5e2232a9-7539-4539-bcad-bd6844b37a64",
    title: "5 sinais de que a sua [ESTRATÉGIA] está travando o seu [RESULTADO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "7ba21a9d-376b-45cd-af28-25631ce8297a",
    title:
      "Esses foram os últimos [RESULTADOS] que meus [ALUNOS/CLIENTES] tiveram",
    niche: [],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "e5bdf27f-b6d6-4476-b6a5-677db5bca506",
    title: "O dia em que percebi que eu mesma era o meu [PROBLEMA]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "c6e61aa6-39b0-428f-8114-ef2810be8577",
    title: "[X] livros que mudaram o meu [NICHO]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "89e3dcf8-1617-4c20-97cf-84de9691872d",
    title: "O erro que te faz sentir que está sempre recomeçando do zero",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "9b5ed0e1-8c80-4a88-ae86-0733c4a942a5",
    title: "Antes de tentar [AÇÃO/TRATAMENTO/INVESTIR], entenda isso primeiro",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "003b12e2-f58a-4ccc-a894-2684f88b003e",
    title: "Frases que você precisa parar de dizer se quer [RESULTADO]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "83413d26-7e3b-41a7-a5e9-a34b90101297",
    title: "[ERROS] que cometi ao aplicar [ESTRATÉGIA] no [NICHO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "6dcaaf37-8e45-49df-b540-4ce4b86e38e2",
    title: "O que eu avalio antes de aceitar alguém na [MENTORIA/SERVIÇO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Mentoria", "Serviço"],
  },
  {
    id: "505371bf-59ef-453b-9745-6cbc99fea0bc",
    title: "Se eu tivesse 30 minutos com você, eu te falaria isso",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "78932812-82bb-48e9-be96-f81cb5fe39d4",
    title: "Antes e depois de fazer um diagnóstico comigo",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "cc539983-057d-47d9-94c7-0fb2e88374f3",
    title:
      "Insights sobre [NICHO/ÁREA] que ninguém te conta (mas eu vou contar)",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "378b91a0-7c94-4400-8762-9f64a18f36c9",
    title:
      "O que ninguém te conta sobre alcançar [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "886fb3ad-537f-489a-bab2-b2d2c47ffb62",
    title: "3 erros que me afastavam do [OBJETIVO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "5c848004-0bb1-47bb-a352-4cc465669d23",
    title:
      "O que eu te diria se você estivesse em uma sessão de diagnóstico comigo",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "3319499b-4f2b-4337-8184-46450d48c188",
    title:
      "Por que a maioria erra na hora de montar uma [ESTRATÉGIA/ABORDAGEM/ROTINA] de [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "e18d8213-41a9-4e31-9379-9ed6d01badee",
    title:
      "Resultados que meus [ALUNOS/CLIENTES/PACIENTES] tiveram depois da [MENTORIA/CONSULTORIA/ACOMPANHAMENTO]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "7d88fe86-5db5-4057-975e-350d8bd7f4af",
    title: "O checklist essencial para começar a [ação] do jeito certo",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "31015858-e458-4b90-ba61-0b35dd951972",
    title:
      "Como eu ajudei [ALUNO/CLIENTE] a sair de [PONTO A] e chegar em [PONTO B]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "5542d069-f6cb-4320-8a2f-08faf18ecd33",
    title: "Erros que estão te impedindo de [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "bb6efa8d-1d2d-4300-9032-23b3957c0e83",
    title:
      "Você está tentando [RESULTADO/OBJETIVO/CONQUISTA], mas está ignorando isso aqui",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "fc20ccfb-8e20-48d9-abcc-596c6bcef137",
    title: "O que eu aprendi sendo [PROFISSÃO] no [NICHO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "40744e9f-0827-477d-aff8-872aac6803e6",
    title: "POV: Você acabou de aplicar o que aprendeu no [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "a3f5f189-d8a0-4b28-b9b8-b3796e56f836",
    title:
      "Ferramentas/sites gratuitos que todo [PROFISSÃO/ESPECIALISTA] deveria conhecer",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "a3473e25-4b79-45b4-a6be-2cb61cdd33ab",
    title: "Tudo que aconteceu no [PRODUTO/SERVIÇO] no mês de [MÊS]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "b34b31a2-3808-4518-97a0-7643ed62c087",
    title: "3 sinais de que você está fazendo [AÇÃO] do jeito errado",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "65dbba78-fbcd-4cff-bc26-9bc9e226d1dc",
    title:
      "Esses são os resultados que você vai ter depois de um diagnóstico comigo",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "91ae3e62-59b4-46ac-bddc-aca3f904330c",
    title:
      "O erro que faz você perder tempo tentando [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "c0a79650-e624-48f4-876c-61920e75dfe4",
    title:
      "O que eu aprendi no [EVENTO/PALESTRA/IMERSÃO] e que você pode aplicar também",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "38d0a94e-f098-42a5-991f-b3ccf46fe3c1",
    title:
      "O que vai acontecer quando você aplicar o [PRODUTO/SERVIÇO] por 7 dias",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "c9e0c9ec-6700-4995-972c-c0b2d18edc8a",
    title:
      "4 passos pra transformar o seu [PROBLEMA/DOR/DIFICULDADE] em [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "edeb003b-e728-46c0-8bf5-1948e8d7e2b2",
    title:
      "Coisas que são óbvias pra mim como [PROFISSÃO/ESPECIALISTA], mas que talvez você não saiba",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "92bd64fa-f0fa-48a3-82ce-e8a60414f7c6",
    title:
      "O dia em que percebi que estava tentando vender pra quem nunca ia comprar de mim",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "8000d0a2-fbca-4e4e-b919-e635212fea6a",
    title:
      "Acabei de terminar uma [SESSÃO/REUNIÃO/CONSULTA/AULA] e tenho que contar o que aconteceu",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: ["Consultoria", "Mentoria", "Serviço"],
  },
  {
    id: "4003d939-e90c-4f2b-9df4-784634d1da38",
    title: "O que você conquista em [TEMPO] depois da [MENTORIA/SERVIÇO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: [],
  },
  {
    id: "424e3889-c953-467a-84d6-f9b81899e246",
    title:
      "A diferença entre o [PROFISSIONAL/ESPECIALISTA] que avança e o que fica no lugar",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: ["Consultoria", "Mentoria", "Produto", "Serviço"],
  },
  {
    id: "bbadd151-3c41-4026-b8a0-cbb362561b27",
    title:
      "[MENTORADOS/CLIENTES/PACIENTES] destaque do mês dentro da [MENTORIA/CONSULTORIA/PROGRAMA]",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "cd96f83d-4ddb-435e-a225-fabac9e93334",
    title: "Troque [HÁBITO ANTIGO] por [HÁBITO CERTO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "b9389d25-0cf9-49fc-9653-342563be46b5",
    title: "O que você vai receber dentro do [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "225448a4-6e41-43d9-bc92-7cfcdcf71925",
    title: "É por isso que você parou de crescer no [NICHO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "02fe2211-b5e1-4a1c-8fd7-222c125ab80f",
    title: "O que ninguém te ensina sobre [AÇÃO]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "d5465b40-0072-4e11-9e1d-ad41a5976323",
    title: "O que muda quando você tem acompanhamento de verdade",
    niche: [],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria", "Serviço"],
  },
  {
    id: "bcd7c422-a798-4f40-bf79-559dc0ce994f",
    title:
      "O erro que faz você acreditar que está avançando em [TEMA], mas não está",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "2007d094-a50c-45e7-a570-a12b6d5f7011",
    title: "Como evitar os principais obstáculos de quem quer [AÇÃO]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "27f41723-ac94-4fd7-8793-0f021cff055b",
    title:
      "Entregáveis da minha [MENTORIA/CONSULTORIA/ACOMPANHAMENTO] que você ainda não conhece",
    niche: [
      "Designer",
      "Direito",
      "Educação",
      "Gestor de Tráfego",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Social Media",
      "Universal",
    ],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "88dcaa72-934c-473e-a95a-14961ed80fb2",
    title: "Você não precisa de mais uma estratégia, precisa de clareza",
    niche: ["Universal"],
    goal: "Vender",
    productType: [],
  },
  {
    id: "cfa7ec52-efaf-4af3-83d3-bcc391365720",
    title: "O que realmente acontece dentro do [PRODUTO/SERVIÇO].",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "310b6503-2d38-4fff-8d05-42f7c4f1f7fb",
    title:
      "O que eu nunca faria se fosse contratar um [PROFISSIONAL/ESPECIALISTA] na minha área",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: ["Consultoria", "Mentoria", "Serviço"],
  },
  {
    id: "3c4f2935-52a9-493b-81ba-c55d872fbfc7",
    title:
      "Por que você ainda não conseguiu [RESULTADO] — mesmo já sabendo o que precisa fazer",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [],
  },
  {
    id: "b53e4b8d-7ce3-48aa-9626-3fa3c58e43b8",
    title: "Coisas que ninguém te conta sobre [TEMA DA ISCA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "efed17a8-80a0-45b4-9da1-aa211917dffa",
    title:
      "3 erros que estão fazendo o seu [RESULTADO] demorar mais do que deveria",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "e7d93b03-2af6-4146-a47d-130ab40af7b8",
    title:
      "Se você ainda não chegou em [RESULTADO/OBJETIVO/CONQUISTA], leia isso",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "1a07966d-1234-47a4-bf8b-8becd013e68a",
    title: "POV: você está em uma [REUNIÃO/HOTSEAT] comigo",
    niche: ["Universal"],
    goal: "Vender",
    productType: [],
  },
  {
    id: "f0e8e986-2ada-4a5a-a10c-518308a56159",
    title: "5 erros que todo mundo comete ao tentar [AÇÃO] sozinho(a)",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "08ee37d2-d862-4724-9cbd-958d29adbd61",
    title: "Roube as minhas anotações do [EVENTO] e aplique ainda hoje",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "ac7cf137-eb32-4008-8371-189a1e744eda",
    title:
      "Por que o [PRODUTO/SERVIÇO] funciona tão rápido (mesmo pra quem já tentou de tudo)",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "0e51dda8-1b1e-4bdd-977e-bb0e7e285a5a",
    title: "Isso é [PROBLEMA COMUM], isso é [SOLUÇÃO]",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "34c629b4-1842-4e9d-88a1-9355b27d65eb",
    title: "O que você vai receber ao entrar no [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "ad8789ce-be30-4104-bf44-124596011bad",
    title: "O que ninguém te contou sobre [RESULTADO/TRANSFORMAÇÃO/TRATAMENTO]",
    niche: [
      "Direito",
      "Educação",
      "Finanças",
      "Fotografia",
      "Infoprodutor",
      "Marketing",
      "Nutrição",
      "Personal",
      "Prestador de Serviço",
      "Psicologia",
      "Saúde",
      "Universal",
    ],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "7635ad61-578c-488a-b715-fe81aa8504a1",
    title:
      "[X] ferramentas de IA que uso para [AÇÃO/TAREFA] e economizar tempo",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "4152936d-0651-4d21-9669-28ba256ba3b4",
    title:
      "[PRODUTO/MÉTODO/ABORDAGEM] foi questionado por especialistas — e eu analisei",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: ["Consultoria", "Mentoria", "Serviço"],
  },
  {
    id: "a2674a03-2b6e-480f-a43d-63081bc76de2",
    title: "Como organizar [ÁREA/ROTINA/ESTRATÉGIA] em menos de [X] minutos",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "0a4a1883-2b9f-433f-aca8-9818abfcec91",
    title:
      "[X] tipos de conteúdo que eu produzo toda semana — e qual gera mais [V",
    niche: [],
    goal: null,
    productType: [],
  },
  {
    id: "ef9b8ebc-6237-4239-a3f3-be0815dbcb16",
    title:
      "[X] erros que [INICIANTES/PROFISSIONAIS] cometem em [NICHO/ÁREA] (e como evitar)",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "923b46d7-0519-4a91-8d40-c9ab71f5dc9f",
    title:
      "Por que você continua fazendo [AÇÃO/HÁBITO/ESTRATÉGIA] do jeito errado mesmo sabendo o certo",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "58904d20-bb5c-4b41-9b58-af085735199a",
    title:
      "Troque a reunião de [X] horas sem conclusão pelo diagnóstico de [X] min que realmente resolve",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Consultoria"],
  },
  {
    id: "fe894283-53ce-4cfd-aab4-b35bd6a05eff",
    title:
      "O dado sobre [NICHO/ÁREA] que mais me surpreendeu — e o que ele significa para você",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "08db9ba9-1525-4d57-8bf0-aba233f99799",
    title:
      "O guia não convencional para chegar em [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "b60b91f4-2dc6-41b1-b661-3af7c7d39ae2",
    title:
      "O que eu corrijo nas primeiras [X] horas quando começo a trabalhar com alguém",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "5265b2e3-4639-4e51-8da8-6f4b0e34dc48",
    title:
      "O erro que faz [PROFISSÃO] continuar presa em [DOR] mesmo estudando todos os dias",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "a2192c88-ca44-4e8f-98df-ead6bf79a1f8",
    title:
      "O que eu mudei no meu [PERFIL/NEGÓCIO] e parei de perder [SEGUIDOR/CLIENTE] qualificado",
    niche: ["Marketing", "Social Media", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "9216d37a-e47c-4f05-a2cf-595fa83e7d56",
    title: "Ferramentas que eu uso para [NICHO]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "eacc4a32-c9b1-492e-8f1a-80b6d62c495f",
    title:
      "O que os meus [ALUNOS/CLIENTES/PACIENTES] estão falando do [PRODUTO/ATENDIMENTO]?",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "51694893-7add-4329-b076-c6ae806ad6af",
    title: "Como o [PRODUTO/SERVIÇO] mudou o jogo pra [NOME DO ALUNO/CLIENTE]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "fc754dce-a2ab-4e1b-8634-06554fbea7a8",
    title: "O que ninguém te conta sobre ser [PROFISSÃO]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "3bdceaa5-cd80-4cbe-b6fe-76b3e971809a",
    title:
      "Você sabia que [X]% dos [PÚBLICO-ALVO] cometem esse erro em [NICHO/ÁREA]?",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "7a1db680-5e39-4681-81e3-cf5c24dcefd9",
    title:
      "Ninguém te conta isso sobre [RESULTADO/OBJETIVO/CONQUISTA] — mas eu vou contar",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "8dedea67-717b-42ff-8488-ce958a976fc6",
    title:
      "Checklist para saber se o seu [PROJETO/CONTEÚDO/PLANO/TRATAMENTO] está pronto",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "e927a62c-7924-411e-9b6a-8aa8147da9aa",
    title:
      "4 passos simples pra destravar o seu [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "6529d7f7-6c00-47de-943a-43191ac995ee",
    title:
      "Como fazer [AÇÃO/MÉTODO] com um ajuste simples (sem precisar de [OBJEÇÃO/RECURSO])",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "8e11201a-3194-4f90-9849-21d3bf23574b",
    title: "Sinais de que você está fazendo [TEMA DA ISCA] do jeito errado",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "61dd6fc0-eef0-4fcf-bc8b-d8d67507fef7",
    title:
      "[X] perfis/podcasts que todo [PROFISSÃO/ESPECIALISTA] deveria acompanhar",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "d0103df5-4063-4af3-b0bb-36c8bf89fa56",
    title: "As etapas que me levaram até [CONQUISTA/RESULTADO/OBJETIVO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "7fe95ba2-0d6d-48de-9a36-e351b9f32b77",
    title:
      "Coisas que são óbvias pra mim como [PROFISSÃO/ESPECIALISTA] mas que talvez você não saiba",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "fa2e0ae9-9dea-4f77-a141-5ee27b6e1b48",
    title: "O que eu aprendi no [NICHO/MERCADO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "4748102e-30e4-4b06-a023-205e6836f961",
    title: "Detalhes do [PRODUTO/SERVIÇO] que você nem sabia que existia",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "84dc0edf-4756-4e72-b545-dab11a068d64",
    title: "Verdades duras que todo [PÚBLICO-ALVO] precisa ouvir",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "3149c96a-263e-4225-9ddb-c27c424d9d88",
    title: "O básico sobre [AÇÃO/TÉCNICA/TEMA] explicado em menos de 5 minutos",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "7656e8e9-19bf-4563-bc59-b108fb885538",
    title:
      "[X] sinais de que você está perdendo [CLIENTES/PACIENTES/ALUNOS] antes mesmo de responder a primeira mensagem",
    niche: ["Prestador de Serviço", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Serviço"],
  },
  {
    id: "b2cca2da-f53d-4a47-8bcd-6e9a739c59db",
    title:
      "3 passos pra fazer [AÇÃO/MÉTODO/ESTRATÉGIA] render o dobro de [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "e71c2b70-aa62-4c23-8647-fca5d5c24318",
    title:
      "Troque o post que [AÇÃO QUE NÃO CONVERTE] pelo post que faz a pessoa querer [COMPRAR/SEGUIR/CONTRATAR]",
    niche: ["Marketing", "Social Media", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "08fcc3f5-b1b9-4210-9446-89347eea606d",
    title:
      "O que fazer toda semana se você quer [RESULTADO/OBJETIVO/CONQUISTA] consistente",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "0708a6d3-0400-445a-b693-8b487e7d728d",
    title:
      "O que meus [ALUNOS/CLIENTES/PACIENTES] me contaram depois de aplicar o [PRODUTO/SERVIÇO]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "e40a97ec-fbe1-456f-97f5-6fbc3e57834f",
    title:
      "Checklist: você está pronta para escalar ou precisa arrumar a base primeiro?",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Consultoria"],
  },
  {
    id: "076afd0f-af43-4c27-8fee-1707c69b3bfb",
    title:
      "Pare de fazer [AÇÃO COMUM] e comece a fazer [AÇÃO EFICAZ] — a diferença é [PRINCÍPIO-CHAVE]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "be89758b-84d2-4c39-ace7-d0ea261c8184",
    title: "[X] livros que mudaram minha visão sobre [NICHO/ÁREA/TEMA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "8e5d223b-423e-48ff-95d5-c4117b076ce8",
    title: "3 passos pra começar a [AÇÃO] do jeito certo.",
    niche: [],
    goal: "Crescer Seguidores",
    productType: [],
  },
  {
    id: "d03299d6-d22c-4b7d-8e62-161a842e5089",
    title:
      "Checklist: o que fazer antes de [AÇÃO/LANÇAMENTO/ATENDIMENTO/CONSULTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "b957d853-3531-4946-b0d5-2f7b87281aec",
    title:
      "[X] ferramentas/apps que todo [PROFISSÃO/ESPECIALISTA] deveria usar em [ANO/HOJE]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "576b3c8a-6fc0-451e-8a31-a0320316e2f7",
    title:
      "[X] coisas que eu avalio antes de aceitar um novo [CLIENTE/PACIENTE/ALUNO]",
    niche: ["Prestador de Serviço", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Serviço"],
  },
  {
    id: "a58a3c8c-6350-41d0-bba4-b239857d9fb7",
    title:
      "Checklist: seu perfil está pronto para receber [CLIENTE/PACIENTE/ALUNO] hoje?",
    niche: ["Prestador de Serviço", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Serviço"],
  },
  {
    id: "edcad505-3092-42c2-885f-a164a8ed7257",
    title:
      "Troque [AÇÃO GENÉRICA QUE SEU CLIENTE FAZ] por [AÇÃO ESPECÍFICA QUE VOCÊ ENTREGA]",
    niche: ["Prestador de Serviço", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Serviço"],
  },
  {
    id: "b854b1b4-35c9-4377-a7a1-1eb382c8a0ef",
    title:
      "Checklist: sua [LINHA EDITORIAL/ESTRATÉGIA DE CONTEÚDO] está travando suas vendas?",
    niche: ["Infoprodutor", "Marketing", "Social Media", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "9bd2e940-b761-45da-8305-d2acd5db2454",
    title: "O passo a passo pra participar do [PRODUTO/SERVIÇO]",
    niche: [],
    goal: "Vender",
    productType: ["Produto", "Serviço"],
  },
  {
    id: "24618068-6690-4098-ba54-366302ec4d27",
    title:
      "[X] erros que eu vejo em todo [NEGÓCIO/PERFIL/ESTRATÉGIA] antes de uma consultoria",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Consultoria"],
  },
  {
    id: "adf0076a-332e-4422-9503-7fc415cec6fe",
    title:
      "Troque [HÁBITO/AÇÃO ERRADA] por [HÁBITO/AÇÃO CERTA] se você quer [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "a65bf1c4-ca02-4b87-a94b-237ab8e1baad",
    title: "Estratégias que ninguém te conta sobre [X/NICHO/ÁREA]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "4cad880e-8815-4696-a5e1-09566b52c680",
    title: "[X] perguntas para refletir antes de [AÇÃO/DECISÃO/INVESTIMENTO]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "23bab8b4-c594-41dc-9f62-75c90b6b7d0d",
    title:
      "De [DOR] para [DESEJO]: o que muda quando você tem uma [ESTRATÉGIA]",
    niche: [],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "2967feb6-8a4f-4883-964e-8b21313d9b4b",
    title:
      "[X] hábitos que [PROFISSIONAIS/ESPECIALISTAS] de sucesso em [NICHO/ÁREA] têm em comum",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "30bd5220-7a7f-4628-93a4-afdc18f76b6e",
    title:
      "O que meus [ALUNOS/CLIENTES/PACIENTES] fizeram em [X TEMPO] dentro da [MENTORIA/CONSULTORIA/PROGRAMA]",
    niche: ["Universal"],
    goal: "Vender",
    productType: ["Consultoria", "Mentoria"],
  },
  {
    id: "8b550e19-e484-439a-a757-77b77ee11e62",
    title: "4 erros que você comete ao tentar [RESULTADO/OBJETIVO/CONQUISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "635e7a2e-8797-423b-b457-a779c5e27b8e",
    title:
      "Eu achava que o [PROBLEMA] era falta de tempo, até perceber que o que me faltava [RESULTADO]",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "0b232eb8-8510-430b-83a9-30b97ab0eb2f",
    title:
      "O que faz [CLIENTE IDEAL] escolher você e não a [CONCORRENTE/PROFISSIONAL] que cobra mais barato",
    niche: ["Prestador de Serviço", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Consultoria", "Serviço"],
  },
  {
    id: "19cdb77d-d199-4da2-8a5d-0e9e2736b1f3",
    title:
      "[X] conteúdos que me fazem vender [PRODUTO] todos os dias sem [LIVE/LANÇAMENTO/ANÚNCIO]",
    niche: ["Infoprodutor", "Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "719bda67-7bdc-408d-9162-9b9e287c22b6",
    title:
      "O que ninguém te conta sobre por que o [RESULTADO/OBJETIVO/CONQUISTA] não aparece",
    niche: ["Universal"],
    goal: "Gerar Autoridade",
    productType: [
      "Consultoria",
      "Low Ticket",
      "Mentoria",
      "Produto",
      "Serviço",
    ],
  },
  {
    id: "7a630496-d33b-4e03-9507-015798050624",
    title:
      "[X] coisas que eu faria diferente se começasse hoje como [PROFISSÃO/ESPECIALISTA]",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
  {
    id: "01fde46f-7e49-4346-a1f2-33698de7467d",
    title: "Como fazer [AÇÃO/PROCESSO] em [X] passos simples",
    niche: ["Universal"],
    goal: "Crescer Seguidores",
    productType: ["Low Ticket", "Produto"],
  },
] as const;
