export const PHASES = {
  idea: {
    slug: "idea",
    title: "Ideia",
    color: "#fbbf24",
    order: 1,
    shortcut: "i",
    key: "KeyI",
  },
  do: {
    slug: "do",
    title: "Fazer",
    color: "#f97316",
    order: 2,
    shortcut: "f",
    key: "KeyF",
  },
  doing: {
    slug: "doing",
    title: "Fazendo",
    color: "#ec4899",
    order: 3,
    shortcut: "z",
    key: "KeyZ",
  },
  review: {
    slug: "review",
    title: "Análise",
    color: "#a855f7",
    order: 4,
    shortcut: "a",
    key: "KeyA",
  },
  done: {
    slug: "done",
    title: "Feito",
    color: "#38bdf8",
    order: 5,
    shortcut: "t",
    key: "KeyT",
  },
  finished: {
    slug: "finished",
    title: "Concluído",
    color: "#4ade80",
    order: 6,
    shortcut: "c",
    key: "KeyC",
  },
} as const;
export type PHASE = keyof typeof PHASES;
export type PHASE_TYPE = (typeof PHASES)[PHASE];
export const CATEGORIES = {
  ads: {
    slug: "ads",
    title: "Tráfego Pago",
    shortcut: "a",
    color: "#0099ff",
    area: "account",
    tag: "ADS",
    tag_min: "ad",
  },
  capture: {
    slug: "capture",
    title: "Gravação",
    shortcut: "u",
    color: "#00ffc4",
    area: "creative",
    tag: "REC",
    tag_min: "gr",
  },
  carousel: {
    slug: "carousel",
    title: "Carrossel",
    shortcut: "c",
    color: "#ff0071",
    area: "creative",
    tag: "CRSL",
    tag_min: "cr",
  },
  design: {
    slug: "design",
    title: "Design",
    shortcut: "d",
    color: "#ff0080",
    area: "creative",
    tag: "DSGN",
    tag_min: "dg",
  },
  dev: {
    slug: "dev",
    title: "Tech/Coding",
    shortcut: "g",
    color: "#b1ff00",
    area: "creative",
    tag: "TECH",
    tag_min: "tc",
  },
  finance: {
    slug: "finance",
    title: "Financeiro",
    shortcut: "f",
    color: "#46b95d",
    area: "adm",
    tag: "FINC",
    tag_min: "fn",
  },
  meeting: {
    slug: "meeting",
    title: "Reunião",
    shortcut: "m",
    color: "#375bc8",
    area: "account",
    tag: "REUN",
    tag_min: "re",
  },
  post: {
    slug: "post",
    title: "Post Estático",
    shortcut: "p",
    color: "#ff4000",
    area: "creative",
    tag: "POST",
    tag_min: "pt",
  },
  print: {
    slug: "print",
    title: "Impresso",
    shortcut: "i",
    color: "#cc33aa",
    area: "creative",
    tag: "IMPR",
    tag_min: "im",
  },
  reels: {
    slug: "reels",
    title: "Reels",
    shortcut: "r",
    color: "#aa00ff",
    area: "creative",
    tag: "REEL",
    tag_min: "rl",
  },
  sm: {
    slug: "sm",
    title: "Social Media",
    shortcut: "l",
    color: "#ff0015",
    area: "account",
    tag: "SOCI",
    tag_min: "sm",
  },
  stories: {
    slug: "stories",
    title: "Stories",
    shortcut: "s",
    color: "#aacc33",
    area: "creative",
    tag: "STOR",
    tag_min: "st",
  },
  todo: {
    slug: "todo",
    title: "Tarefa",
    shortcut: "t",
    color: "#0088ff",
    area: "account",
    tag: "TASK",
    tag_min: "ta",
  },
} as const;
export type CATEGORY = keyof typeof CATEGORIES;
export type CATEGORY_TYPE = (typeof CATEGORIES)[CATEGORY];
export const PRIORITIES = {
  low: {
    slug: "low",
    title: "Baixa",
    shortcut: ",",
  },
  medium: {
    slug: "medium",
    title: "Média",
    shortcut: ".",
  },
  high: {
    slug: "high",
    title: "Alta",
    shortcut: "/",
  },
} as const;
export type PRIORITY = keyof typeof PRIORITIES;
export type PRIORITY_TYPE = (typeof PRIORITIES)[PRIORITY];
export const AREAS = {
  adm: {
    slug: "adm",
    title: "Administrativo",
    role: 1,
  },
  account: {
    slug: "account",
    title: "Atendimento",
    role: 2,
  },
  creative: {
    slug: "creative",
    title: "Criação",
    role: 3,
  },
} as const;
export type AREA = keyof typeof AREAS;
export type AREA_TYPE = (typeof AREAS)[AREA];
export const SIZE = {
  xs: "xs",
  sm: "sm",
  md: "md",
  lg: "lg",
  xl: "xl",
  "2xl": "2xl",
} as const;
export const DATE_TIME_DISPLAY = {
  Relative: 1,
  DateTime: 2,
  DateMonthTime: 3,
  DayDateMonthTime: 4,
  DayDate: 5,
  TimeOnly: 6,
  DateOnly: 7,
  Null: 8,
} as const;
export const VARIANT = {
  line: "line",
  block: "block",
  content: "content",
  hair: "hair",
} as const;
export const INTENT = {
  create_action: "create-action",
  update_action: "update-action",
  bulk_update_actions: "bulk-update-actions",
  bulk_update_date_only: "bulk-update-date-only",
  bulk_update_time_only: "bulk-update-time-only",
  duplicate_action: "duplicate-action",
  delete_action: "delete-action",
  create_comment: "create-comment",
  update_comment: "update-comment",
  delete_comment: "delete-comment",
  ai_caption: "ai-caption",
  ai_content: "ai-content",
  ai_hooks: "ai-hooks",
  ai_strategy: "ai-strategy",
  ai_post: "ai-post",
  ai_carousel: "ai-carousel",
  ai_stories: "ai-stories",
  ai_reels: "ai-reels",
  mark_notification_read: "mark-notification-read",
  mark_all_notifications_read: "mark-all-notifications-read",
} as const;
export const ORDER_BY = {
  date: "date",
  priority: "priority",
  phase: "phase",
} as const;
