export const PALLETE = [
  {
    id: "default",
    label: "Padrão",
    light: {
      primary: {
        h: 0,
        c: 0,
        l: 0,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 200,
        c: 0.002,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.1,
      popoverLDelta: 0.02,
    },
    dark: {
      primary: {
        h: 0,
        c: 0,
        l: 1,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 250,
        c: 0.01,
        l: 0.2,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.1,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "energy",
    label: "Energy",
    light: {
      primary: {
        h: 120,
        c: 0.26,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 240,
        c: 0.001,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 120,
        c: 0.26,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 250,
        c: 0.01,
        l: 0.2,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "blue",
    label: "Azul (Padrão)",
    light: {
      primary: {
        h: 264,
        c: 0.31,
        l: 0.45,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 1,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: -0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0.1,
    },
    dark: {
      primary: {
        h: 264,
        c: 0.31,
        l: 0.58,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "purple",
    label: "Roxo",
    light: {
      primary: {
        h: 290,
        c: 0.28,
        l: 0.54,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 1,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.1,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 290,
        c: 0.28,
        l: 0.68,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "magenta",
    label: "Magenta",
    light: {
      primary: {
        h: 350,
        c: 0.4,
        l: 0.9,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 320,
        c: 0.02,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 350,
        c: 0.4,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 340,
        c: 0.1,
        l: 0.3,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "red",
    label: "Vermelho",
    light: {
      primary: {
        h: 20,
        c: 0.25,
        l: 0.62,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.04,
      actionHoverLDelta: 0.06,
      popoverLDelta: 0.06,
    },
    dark: {
      primary: {
        h: 20,
        c: 0.25,
        l: 0.68,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "orange",
    label: "Laranja",
    light: {
      primary: {
        h: 25,
        c: 0.18,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 130,
        c: 0.01,
        l: 0.95,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 1,
      popoverLDelta: 0.03,
    },
    dark: {
      primary: {
        h: 25,
        c: 0.18,
        l: 0.65,
      },
      primaryFg: {
        h: 130,
        c: 0.02,
        l: 0.9,
      },
      bg: {
        h: 190,
        c: 0.01,
        l: 0.25,
      },
      fg: {
        h: 130,
        c: 0.01,
        l: 0.95,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.1,
      inputLDelta: -0.05,
      actionLDelta: 0.07,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "yellow",
    label: "Amarelo",
    light: {
      primary: {
        h: 100,
        c: 0.5,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 100,
        c: 0.4,
        l: 0.8,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "green",
    label: "Verde",
    light: {
      primary: {
        h: 130,
        c: 0.2,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 130,
        c: 0.2,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "cyan",
    label: "Ciano",
    light: {
      primary: {
        h: 200,
        c: 0.2,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.96,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 200,
        c: 0.2,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "light-blue",
    label: "Azul Claro",
    light: {
      primary: {
        h: 260,
        c: 0.22,
        l: 0.7,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 0,
        c: 0,
        l: 0.98,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 240,
        c: 0.22,
        l: 0.65,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 0,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
  {
    id: "navy",
    label: "Azul Marinho",
    light: {
      primary: {
        h: 250,
        c: 0.12,
        l: 0.5,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 90,
        c: 0.005,
        l: 0.99,
      },
      fg: {
        h: 0,
        c: 0,
        l: 0,
      },
      cardLDelta: -0.02,
      secondaryLDelta: -0.04,
      mutedLDelta: -0.02,
      borderLDelta: -0.05,
      inputLDelta: -0.05,
      actionLDelta: 0.02,
      actionHoverLDelta: 0.04,
      popoverLDelta: 0,
    },
    dark: {
      primary: {
        h: 250,
        c: 0.12,
        l: 0.6,
      },
      primaryFg: {
        h: 0,
        c: 0,
        l: 1,
      },
      bg: {
        h: 285,
        c: 0.005,
        l: 0.141,
      },
      fg: {
        h: 0,
        c: 0,
        l: 1,
      },
      cardLDelta: 0.05,
      secondaryLDelta: 0.06,
      mutedLDelta: 0.03,
      borderLDelta: 0.2,
      inputLDelta: 0.05,
      actionLDelta: 0.1,
      actionHoverLDelta: 0.2,
      popoverLDelta: -0.03,
    },
  },
];
